name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grand execute permission to gradle
        run: chmod +x gradlew

      - name: Build with gradlew
        run: ./gradlew build

      - name: Build and push image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: truefunnny/test-repo
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


